### ISSUE TITLE
Faire apparaître la date sur le gif

### ISSUE THREAD

**Issue by fmassot** [regardscitoyens/ND2017-synthese-gif#2]
Je n'ai pas vu de date sur le gif, c'est bien utile pour suivre l'évolution

**Comment by RouxRC** [comment]
c'est un peu galère à regénérer chaque image a posteriori, par contre on peut ptet intégrer un texte à partir du nom de chaque fichier image dans la génération du gif avec convert ?

**Comment by fmassot** [comment]
oui ça doit être la meilleure solution de rajouter le texte avant la génération du gif
